### ISSUE TITLE
内存错误

### ISSUE THREAD

**Issue by sunmenghua** [SeasX/SeasLog#76]
PHP Version 7.0.2
SeasLog Version 1.5.1

```
$array = ['key' => 'test array'];
SeasLog::debug('SeasLog Test: {var}', ['{var}' => $array['key']]);
```

bt:

```
Core was generated by `php-fpm: pool www                                                             '.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f7e163f9e63 in seaslog_log_by_level_common (execute_data=0x7f7e16e162d0, return_value=0x7f7e16e162b0, level=0x7f7e163fb7aa "debug")
    at /home/vagrant/SeasLog/seaslog.c:850
850         if (_seaslog_log_content(argc, level, ZSTR_VAL(message), ZSTR_LEN(message), HASH_OF(content), ZSTR_VAL(logger), ZSTR_LEN(logger), seaslog_ce TSRMLS_CC) == FAILURE) {
(gdb) bt
#0  0x00007f7e163f9e63 in seaslog_log_by_level_common (execute_data=0x7f7e16e162d0, return_value=0x7f7e16e162b0, level=0x7f7e163fb7aa "debug")
    at /home/vagrant/SeasLog/seaslog.c:850
#1  0x00007f7e163fabf8 in zim_SEASLOG_RES_NAME_debug (execute_data=0x7f7e16e162d0, return_value=0x7f7e16e162b0) at /home/vagrant/SeasLog/seaslog.c:1147
#2  0x0000000000940c4f in execute_internal (execute_data=0x7f7e16e162d0, return_value=0x7f7e16e162b0)
    at /home/vagrant/php-7.0.2/Zend/zend_execute.c:2036
#3  0x00000000008cc35e in dtrace_execute_internal (execute_data=0x7f7e16e162d0, return_value=0x7f7e16e162b0)
    at /home/vagrant/php-7.0.2/Zend/zend_dtrace.c:107
#4  0x00000000009433f1 in ZEND_DO_FCALL_SPEC_HANDLER (execute_data=0x7f7e16e16220) at /home/vagrant/php-7.0.2/Zend/zend_vm_execute.h:844
#5  0x0000000000942242 in execute_ex (ex=0x7f7e16e16220) at /home/vagrant/php-7.0.2/Zend/zend_vm_execute.h:417
#6  0x00000000008cc2c0 in dtrace_execute_ex (execute_data=0x7f7e16e16220) at /home/vagrant/php-7.0.2/Zend/zend_dtrace.c:83
#7  0x00000000008cf6f8 in zend_call_function (fci=0x7fff5929c0a0, fci_cache=0x7fff5929c0f0) at /home/vagrant/php-7.0.2/Zend/zend_execute_API.c:860
#8  0x000000000090c88a in zend_call_method (object=0x7fff5929c260, obj_ce=0x7f7e16e087b8, fn_proxy=0x0, function_name=0x7f7e16e75b18 "indexaction", 
    function_name_len=11, retval_ptr=0x7fff5929c240, param_count=0, arg1=0x0, arg2=0x0) at /home/vagrant/php-7.0.2/Zend/zend_interfaces.c:104
#9  0x00007f7e16614fad in yaf_dispatcher_handle (dispatcher=0x7f7e16e6b0f8, request=0x7f7e16e75848, response=0x7fff5929c4d0, view=0x7fff5929c3a0)
    at /home/vagrant/yaf/yaf_dispatcher.c:605
#10 0x00007f7e16616779 in yaf_dispatcher_dispatch (dispatcher=0x7f7e16e6b0f8, response_ptr=0x7fff5929c4d0) at /home/vagrant/yaf/yaf_dispatcher.c:878
#11 0x00007f7e1661136e in zim_yaf_application_run (execute_data=0x7f7e16e161c0, return_value=0x7f7e16e161b0) at /home/vagrant/yaf/yaf_application.c:444
#12 0x0000000000940c4f in execute_internal (execute_data=0x7f7e16e161c0, return_value=0x7f7e16e161b0)
    at /home/vagrant/php-7.0.2/Zend/zend_execute.c:2036
#13 0x00000000008cc35e in dtrace_execute_internal (execute_data=0x7f7e16e161c0, return_value=0x7f7e16e161b0)
    at /home/vagrant/php-7.0.2/Zend/zend_dtrace.c:107
#14 0x00000000009433f1 in ZEND_DO_FCALL_SPEC_HANDLER (execute_data=0x7f7e16e16030) at /home/vagrant/php-7.0.2/Zend/zend_vm_execute.h:844
#15 0x0000000000942242 in execute_ex (ex=0x7f7e16e16030) at /home/vagrant/php-7.0.2/Zend/zend_vm_execute.h:417
#16 0x00000000008cc2c0 in dtrace_execute_ex (execute_data=0x7f7e16e16030) at /home/vagrant/php-7.0.2/Zend/zend_dtrace.c:83
#17 0x000000000094236c in zend_execute (op_array=0x7f7e16e75000, return_value=0x0) at /home/vagrant/php-7.0.2/Zend/zend_vm_execute.h:458
#18 0x00000000008e6e65 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /home/vagrant/php-7.0.2/Zend/zend.c:1427
#19 0x0000000000853d41 in php_execute_script (primary_file=0x7fff5929ebf0) at /home/vagrant/php-7.0.2/main/main.c:2471
#20 0x00000000009bcb88 in main (argc=6, argv=0x7fff5929ee18) at /home/vagrant/php-7.0.2/sapi/fpm/fpm/fpm_main.c:1944
```

**Comment by sunmenghua** [comment]
@Neeke

**Comment by Neeke** [comment]
收到。

2016-02-16 10:08 GMT+08:00 孙梦华 notifications@github.com:

**Comment by Neeke** [comment]
fixed with #80
